/*
    시험 문제
    NOTICE 테이블 만들기
*/

CREATE TABLE NOTICE(
    NOTICENO NUMBER NOT NULL,
    NOTICETITLE VARCHAR2(20) NOT NULL,
    NOTICEDATE DATE DEFAULT SYSDATE,
    NOTICEWRITER VARCHAR2(15) NOT NULL,
    NOTICECONTENT VARCHAR2(2000),
    ORIGINAL_FILEPATH VARCHAR2(100),
    RENAME_FILEPATH VARCHAR2(100)
);


COMMENT ON COLUMN NOTICE.NOTICENO IS '공지글번호';
COMMENT ON COLUMN NOTICE.NOTICETITLE IS '공지글제목';
COMMENT ON COLUMN NOTICE.NOTICEDATE IS '공지글등록날짜';
COMMENT ON COLUMN NOTICE.NOTICEWRITER IS '공지글작성자아이디';
COMMENT ON COLUMN NOTICE.NOTICECONTENT IS '공지글내용';
COMMENT ON COLUMN NOTICE.ORIGINAL_FILEPATH IS '첨부파일명';
COMMENT ON COLUMN NOTICE.RENAME_FILEPATH IS '변경된첨부파일명';

INSERT INTO NOTICE VALUES(1, '아아', '20210203', '이선영', '아아', NULL, NULL);
INSERT INTO NOTICE VALUES(2, '어어', SYSDATE, '강선영', '우우', NULL, NULL);

--ROWNUM
SELECT ROWNUM, N.*
FROM (SELECT *
        FROM NOTICE
        ORDER BY NOTICEDATE DESC) N
WHERE ROWNUM <= 5;

--RANK()
SELECT *
FROM (SELECT NOTICENO, NOTICETITLE, NOTICEDATE, NOTICEWRITER
           , NOTICECONTENT, ORIGINAL_FILEPATH, RENAME_FILEPATH
           , RANK() OVER(ORDER BY NOTICEDATE DESC) "순위"
        FROM NOTICE)
WHERE 순위 <= 5;









