
CREATE TABLE DEPARTMENT(
    DEPT_ID CHAR(2) PRIMARY KEY,
    DEPT_TITLE VARCHAR2(35) NOT NULL,
    LOCATION_ID NUMBER REFERENCES LOCATION
);

CREATE TABLE EMPLOYEE(
    EMP_ID VARCHAR2(3) PRIMARY KEY,
    EMP_NAME VARCHAR2(20) NOT NULL,
    EMP_NO VARCHAR2(14) NOT NULL,
    EMAIL VARCHAR2(25),
    PHONE VARCHAR2(12),
    DEPT_CODE CHAR(2) REFERENCES DEPARTMENT(DEPT_ID),
    JOB_CODE CHAR(2) REFERENCES JOB,
    SALARY NUMBER,
    BONUS NUMBER,
    MANAGER_ID VARCHAR2(3),
    HIRE_DATE DATE,
    ENT_DATE DATE,
    ENT_YN CHAR(1) DEFAULT 'N'
);

CREATE TABLE JOB(
    JOB_CODE CHAR(2) CONSTRAINT JC_PK PRIMARY KEY,
    JOB_NAME VARCHAR2(35) NOT NULL
);

CREATE TABLE LOCATION(
    LOCAL_CODE NUMBER PRIMARY KEY,
    NATIONAL_CODE CHAR(2) NOT NULL,
    LOCAL_NAME VARCHAR2(40) NOT NULL
);

DROP TABLE NATIONAL;

CREATE TABLE NATIONAL(
    NATIONAL_CODE CHAR(2) CONSTRAINT LC_PK PRIMARY KEY,
    NATIONAL_NAME VARCHAR2(35) NOT NULL
);

CREATE TABLE SAL_GRADE(
    SAL_LEVEL CHAR(2) PRIMARY KEY,
    MIN_SAL NUMBER,
    MAX_SAL NUMBER
);






