
-- 1.
CREATE TABLE TB_CATEGORY(
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);

-- 2.
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
);

-- 3.
ALTER TABLE TB_CATEGORY 
ADD PRIMARY KEY(NAME);

-- 4.
ALTER TABLE TB_CLASS_TYPE
MODIFY NAME NOT NULL;

-- 5.
ALTER TABLE TB_CATEGORY 
MODIFY NAME VARCHAR2(20);

ALTER TABLE TB_CLASS_TYPE
MODIFY NO VARCHAR2(10)
MODIFY NAME VARCHAR2(20);

-- 6.
ALTER TABLE TB_CATEGORY
RENAME COLUMN NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN NO TO CLASS_TYPE_NO;

ALTER TABLE TB_CATEGORY
RENAME COLUMN TB_NAME TO CATEGORY_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN TB_NAME TO CLASS_TYPE_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME COLUMN TB_NO TO CLASS_TYPE_NO;

-- 7.

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT SYS_C007256 TO PK_NAME;

ALTER TABLE TB_CLASS_TYPE
RENAME CONSTRAINT SYS_C007257 TO PK_CLASS_TYPE_NO;

ALTER TABLE TB_CATEGORY
RENAME CONSTRAINT PK_NAME TO PK_CATEGORY_NAME;

-- 8.
INSERT INTO TB_CATEGORY VALUES ('공학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('자연과학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('의학', 'Y');
INSERT INTO TB_CATEGORY VALUES ('예체능', 'Y');
INSERT INTO TB_CATEGORY VALUES ('인문사회', 'Y');
COMMIT;

-- 9.
ALTER TABLE TB_DEPARTMENT
MODIFY CATEGORY CONSTRAINT FK_DEPARTMENT_CATEGORY REFERENCES TB_CATEGORY(CATEGORY_NAME);


-- 10.
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT;

GRANT CREATE VIEW TO HOMEWORK;

SELECT *
FROM VW_학생일반정보;
     
-- 11.
CREATE OR REPLACE VIEW VW_지도면담
AS SELECT STUDENT_NAME, DEPARTMENT_NAME, PROFESSOR_NAME
     FROM TB_STUDENT S
     LEFT JOIN TB_PROFESSOR P ON (COACH_PROFESSOR_NO = PROFESSOR_NO)
     JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
     ORDER BY DEPARTMENT_NAME;
     
SELECT *
FROM VW_지도면담;

-- 12.
CREATE OR REPLACE VIEW VW_학과별학생수
AS SELECT DEPARTMENT_NAME, COUNT(STUDENT_NO) "STUDENT_COUNT"
     FROM TB_STUDENT S
     JOIN TB_DEPARTMENT D ON (S.DEPARTMENT_NO = D.DEPARTMENT_NO)
     GROUP BY DEPARTMENT_NAME;
     
SELECT *
FROM VW_학과별학생수;

-- 13.
UPDATE VW_학생일반정보
SET STUDENT_NAME = '이선영'
WHERE STUDENT_NO = 'A213046';

SELECT *
FROM VW_학생일반정보
WHERE STUDENT_NO = 'A213046';

-- 14.
CREATE OR REPLACE VIEW VW_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT
WITH READ ONLY;
    

     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     

