
-- 1.
INSERT INTO TB_CLASS_TYPE VALUES(01, '전공필수');
INSERT INTO TB_CLASS_TYPE VALUES(02, '전공선택');
INSERT INTO TB_CLASS_TYPE VALUES(03, '교양필수');
INSERT INTO TB_CLASS_TYPE VALUES(04, '교양선택');
INSERT INTO TB_CLASS_TYPE VALUES(05, '논문지도');

-- 2.
CREATE TABLE TB_학생일반정보
AS SELECT STUDENT_NO, STUDENT_NAME, STUDENT_ADDRESS
     FROM TB_STUDENT;

-- 3.
CREATE TABLE TB_국어국문학과
AS SELECT STUDENT_NO "학번"
        , STUDENT_NAME "학생이름"
        , 19 || (SUBSTR(STUDENT_SSN,1,2)) "출생년도"
        , PROFESSOR_NAME "교수이름"
     FROM TB_STUDENT
     LEFT JOIN TB_PROFESSOR ON (COACH_PROFESSOR_NO = PROFESSOR_NO);

-- 4. UPDATE 사용
UPDATE TB_DEPARTMENT
SET CAPACITY = ROUND(CAPACITY * 1.1);

-- 5.
UPDATE TB_STUDENT
SET STUDENT_ADDRESS = '서울시 종로구 숭인동 181-21'
WHERE STUDENT_NO = 'A413042';

-- 6.
UPDATE TB_STUDENT
SET STUDENT_SSN = SUBSTR(STUDENT_SSN, 1, 6);

-- 7. ★
UPDATE TB_GRADE
SET POINT = 3.5
WHERE (CLASS_NAME, STUDENT_NAME) 
        IN (
           SELECT CLASS_NAME, STUDENT_NAME
             FROM TB_CLASS
             JOIN TB_GRADE USING (CLASS_NO)
             JOIN TB_STUDENT USING (STUDENT_NO)
            WHERE CLASS_NAME = '피부생리학' 
              AND STUDENT_NAME = '김명훈'
            );

-- 8. ★
DELETE FROM TB_GRADE
WHERE ABSENCE_YN IN (SELECT *
                       FROM TB_GRADE
                       JOIN TB_STUDENT USING (STUDENT_NO)
                      WHERE ABSENCE_YN = 'Y');










