
-- 1. 학과명, 계열
SELECT DEPARTMENT_NAME "학과명", CATEGORY "계열"
FROM TB_DEPARTMENT;

-- 2. 학과별정원
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' "학과별 정원"
FROM TB_DEPARTMENT;

-- 3. 휴학생
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO =001 
  AND ABSENCE_YN='Y' 
  AND SUBSTR(STUDENT_SSN, 8, 1) = 2;

-- 4. 도서 장기 연체자
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO = 'A513079' OR STUDENT_NO = 'A513090' OR STUDENT_NO = 'A513091' OR
    STUDENT_NO = 'A513110' OR STUDENT_NO = 'A513119'
ORDER BY 1 DESC;
    
-- 5. 입학정원
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY >= 20 AND CAPACITY <= 30;

-- 6. 총장
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7. 학과가 없는 학생
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8. 선수과목
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9. 계열
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT
ORDER BY 1;

-- 10. 전주 거주자
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' 
    AND SUBSTR(STUDENT_ADDRESS,1,2)='전주' 
    AND SUBSTR(ENTRANCE_DATE,1,2)='02';



