-- 1.
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", ENTRANCE_DATE "입학년도"
FROM TB_STUDENT
ORDER BY ENTERANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3. 만나이 구하기
SELECT PROFESSOR_NAME, EXTRACT(YEAR FROM SYSDATE) - (19||(SUBSTR(PROFESSOR_SSN, 1, 2))) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;

-- 이해불가!! ㅠㅠ
SELECT PROFESSOR_NAME "교수이름", 
       TRUNC(MONTHS_BETWEEN(TRUNC(SYSDATE), TO_DATE('19'||SUBSTR(PROFESSOR_SSN, 1, 6),'YYYYMMDD'))/12) "나이"
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8, 1) = '1'
ORDER BY 2;


SELECT PROFESSOR_NAME, '19'||SUBSTR(PROFESSOR_SSN, 1, 6)
FROM TB_PROFESSOR;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2,2) "이름"
FROM TB_PROFESSOR;
 
-- 5.
SELECT STUDENT_NO, STUDENT_NAME 
FROM TB_STUDENT
WHERE TO_CHAR(ENTRANCE_DATE,'YYYY')-TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,2),'RRRR'),'RRRR')>19;

-- 6. 금요일
SELECT TO_CHAR(TO_DATE(20201225, 'YYMMDD'), 'DAY')
FROM DUAL;

-- 7. 2099년 10월 11일, 2049년 10월 11일 / 1999년 10월 11일, 2049년 10월 11일
SELECT TO_CHAR(TO_DATE('99/10/11','YY/MM/DD'),'YYYY') "99YY",  
       TO_CHAR(TO_DATE('49/10/11','YY/MM/DD'),'YYYY') "49YY",
       TO_CHAR(TO_DATE('99/10/11','RR/MM/DD'),'RRRR') "99RR",
       TO_CHAR(TO_DATE('49/10/11','RR/MM/DD'),'RRRR') "49RR"
FROM DUAL;

-- 8. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

-- 9.
SELECT ROUND(AVG(POINT),1) "평점"
FROM TB_STUDENT
JOIN TB_GRADE USING (STUDENT_NO)
WHERE STUDENT_NO = 'A517178';

-- 10.
SELECT DEPARTMENT_NO, COUNT(*)
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT),1) "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO, 1, 4)
ORDER BY SUBSTR(TERM_NO, 1, 4);

-- 13.
SELECT DEPARTMENT_NO "학과코드명", COUNT(DECODE(ABSENCE_YN, 'Y', 1, 'N', NULL)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 14. 
SELECT STUDENT_NAME "동일이름", COUNT(*) "동명인 수"
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1;











