/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.65
 * Generated at: 2021-06-18 08:23:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .outer{\r\n");
      out.write("        background:rgb(175, 194, 230);\r\n");
      out.write("        color: rgb(247, 247, 247);\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 50px;\r\n");
      out.write("    }\r\n");
      out.write("    #mypage table{margin:auto;}\r\n");
      out.write("    #mypage input{margin:5px;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"outer\">\r\n");
      out.write("        <br>\r\n");
      out.write("        <h2 align=\"center\">마이페이지</h2>\r\n");
      out.write("    \r\n");
      out.write("        <form action=\"update.me\" id=\"mypage\" method=\"post\">\r\n");
      out.write("    \r\n");
      out.write("            <!-- 아이디, 비번, 이름, 전화번호, 이메일, 주소, 취미 -->\r\n");
      out.write("            <table>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>* 아이디</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"userId\" maxlength=\"12\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                \r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>* 이름</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"userName\" maxlength=\"6\" required value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>&nbsp;&nbsp;전화번호</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"phone\" placeholder=\"- 포함해서 입력\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.phone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>&nbsp;&nbsp;이메일</td>\r\n");
      out.write("                    <td><input type=\"email\" name=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>&nbsp;&nbsp;주소</td>\r\n");
      out.write("                    <td><input type=\"text\" name=\"address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.address}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></td>\r\n");
      out.write("                    <td></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>&nbsp;&nbsp;관심분야</td>\r\n");
      out.write("                    <td colspan=\"2\">\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"sports\" value=\"운동\">\r\n");
      out.write("                        <label for=\"sports\">운동</label>\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"climbing\" value=\"등산\">\r\n");
      out.write("                        <label for=\"climbing\">등산</label>\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"fishing\" value=\"낚시\">\r\n");
      out.write("                        <label for=\"fishing\">낚시</label>\r\n");
      out.write("    \r\n");
      out.write("                        <br>\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"cooking\" value=\"요리\">\r\n");
      out.write("                        <label for=\"cooking\">요리</label>\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"game\" value=\"게임\">\r\n");
      out.write("                        <label for=\"game\">게임</label>\r\n");
      out.write("    \r\n");
      out.write("                        <input type=\"checkbox\" name=\"interest\" id=\"movie\" value=\"영화\">\r\n");
      out.write("                        <label for=\"movie\">영화</label>\r\n");
      out.write("    \r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            <script>\r\n");
      out.write("            \t$(function(){\r\n");
      out.write("            \t\tvar interest = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.interest}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            \t\t// \"\" | \"운동,등산,게임\"\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t\t$(\"input[type=checkbox]\").each(function(){\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t// 순차적으로 접근한 input요소의 value값이 interest에 포함되어있을 경우\r\n");
      out.write("            \t\t\t// => 해당 input요소에 checked속성 부여\r\n");
      out.write("                        if(interest.search($(this).val()) != -1){\r\n");
      out.write("                            $(this).attr(\"checked\", true);\r\n");
      out.write("                        } \r\n");
      out.write("\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t});\r\n");
      out.write("            \t\t\r\n");
      out.write("            \t});\r\n");
      out.write("            </script>\r\n");
      out.write("    \r\n");
      out.write("            <br><br>\r\n");
      out.write("    \r\n");
      out.write("            <div align=\"center\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-secondary btn-sm\">정보변경</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-warning btn-sm\" data-toggle=\"modal\" data-target=\"#updatePwdForm\">비밀번호변경</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-danger btn-sm\" data-toggle=\"modal\" data-target=\"#deleteForm\">회원탈퇴</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <br><br>\r\n");
      out.write("        </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 회원탈퇴 버튼 클릭시 보여질 Modal -->\r\n");
      out.write("\t<div class=\"modal\" id=\"deleteForm\">\r\n");
      out.write("\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal Header -->\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h4 class=\"modal-title\">회원탈퇴</h4>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal body -->\r\n");
      out.write("\t      <div class=\"modal-body\" align=\"center\">\r\n");
      out.write("\t        \r\n");
      out.write("\t        <b>탈퇴 후 복구가 불가능합니다. <br>정말로 탈퇴 하시겠습니까?</b> <br><br>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <form action=\"delete.me\" method=\"post\">\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t        \t비밀번호 : <input type=\"password\" name=\"userPwd\" required>\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t<br><br>\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t<button type=\"submit\" class=\"btn btn-danger btn-sm\">탈퇴하기</button>\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t        \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 부트스트랩 사용 -->\r\n");
      out.write("\t<!-- 비밀번호 변경 버튼 클릭시 보여질 Modal -->\r\n");
      out.write("\t<div class=\"modal\" id=\"updatePwdForm\">\r\n");
      out.write("\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t    <div class=\"modal-content\">\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal Header -->\r\n");
      out.write("\t      <div class=\"modal-header\">\r\n");
      out.write("\t        <h4 class=\"modal-title\">비밀번호 변경</h4>\r\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t      <!-- Modal body -->\r\n");
      out.write("\t      <div class=\"modal-body\" align=\"center\">\r\n");
      out.write("\t        \r\n");
      out.write("\t        <form action=\"updatePwd.me\" method=\"post\">\r\n");
      out.write("\t        \r\n");
      out.write("\t        \t<!-- 현재비밀번호, 변경할비밀번호, 변경할비밀번호 재입력 -->\r\n");
      out.write("\t        \t<input type=\"hidden\" name=\"userId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t        \t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>현재 비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"userPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>변경할 비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"updatePwd\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>변경할 비밀번호 재입력</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"checkPwd\" required></td>\r\n");
      out.write("\t\t\t\t\t</tr>\t        \t\t\r\n");
      out.write("\t        \t</table>\r\n");
      out.write("\t        \t<br>\r\n");
      out.write("\t        \t<button type=\"submit\" class=\"btn btn-secondary btn-sm\" onclick=\"return validatePwd();\">비밀번호 변경</button>\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        </form>\r\n");
      out.write("\t        \r\n");
      out.write("\t        <script>\r\n");
      out.write("\t        \tfunction validatePwd(){\r\n");
      out.write("\t        \t\t\r\n");
      out.write("\t        \t\tif($(\"input[name=updatePwd]\").val() != $(\"input[name=checkPwd]\").val()){\r\n");
      out.write("\t        \t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t        \t\t\treturn false; // 비밀번호 변경 요청이 안되게 막음\r\n");
      out.write("\t        \t\t}\r\n");
      out.write("\t        \t\t\r\n");
      out.write("\t        \t}\r\n");
      out.write("\t        </script>\r\n");
      out.write("\t        \r\n");
      out.write("\t        \r\n");
      out.write("\t      </div>\r\n");
      out.write("\t\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
